name: Integration

on:
  push:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays at 02:00


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test to html files.
      uses: Cyb3r-Jak3/html5validator-action@v0.4
      with:
        root: src/
