name: Integration

on:
  push:
    branches:
      - master
      - test-github-actions
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays at 02:00


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # - name: HTML5 Validator
    #   uses: Cyb3r-Jak3/html5validator-action@v0.4
    #   with:
    #     root: src/
    - run: npm install
      working-directory: ./
    - run: ls -R
      working-directory: ./
    - uses: pCYSl5EDgo/cat@master
      id: log
      with:
        path: log.log
      env:
        TEXT: ${{ steps.log.outputs.text }}
    - uses: actions/upload-artifact@v1
      with:
        name: log
        path: log.log
    # - uses: actions/checkout@master
    # - name: Tests Integration with Github Actions.
    #   uses: Cyb3r-Jak3/html5validator-action@v0.4
    #   with:
    #     root: ./src/
    #     log_level: INFO